import { sql } from "drizzle-orm";
import { index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";
export const profiles = sqliteTable("profiles", { userId:text("user_id").primaryKey(), email:text("email").notNull(), displayName:text("display_name").notNull(), jobTitle:text("job_title").notNull().default(""), timezone:text("timezone").notNull().default("Asia/Kolkata"), bio:text("bio").notNull().default(""), createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`), updatedAt:text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`) }, t=>[uniqueIndex("idx_profiles_email").on(t.email)]);
export const projects = sqliteTable("projects", { id:integer("id").primaryKey({autoIncrement:true}), name:text("name").notNull(), key:text("project_key").notNull().unique(), description:text("description").notNull().default(""), ownerId:text("owner_id").notNull(), createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`), updatedAt:text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`) }, t=>[index("idx_projects_owner").on(t.ownerId)]);
export const projectMembers = sqliteTable("project_members", { id:integer("id").primaryKey({autoIncrement:true}), projectId:integer("project_id").notNull().references(()=>projects.id,{onDelete:"cascade"}), userEmail:text("user_email").notNull(), userId:text("user_id"), role:text("role").notNull().default("viewer"), addedAt:text("added_at").notNull().default(sql`CURRENT_TIMESTAMP`) }, t=>[uniqueIndex("idx_project_member_email").on(t.projectId,t.userEmail),index("idx_project_member_user").on(t.userId)]);
export const tickets = sqliteTable("tickets", { id:integer("id").primaryKey({autoIncrement:true}), projectId:integer("project_id").references(()=>projects.id,{onDelete:"set null"}), key:text("ticket_key").notNull().unique(), title:text("title").notNull(), description:text("description").notNull().default(""), project:text("project").notNull().default("General"), issueType:text("issue_type").notNull().default("Task"), status:text("status").notNull().default("To Do"), priority:text("priority").notNull().default("Medium"), reporterId:text("reporter_id").notNull(), assigneeId:text("assignee_id"), assigneeName:text("assignee_name").notNull().default("Unassigned"), progress:integer("progress").notNull().default(0), storyPoints:integer("story_points"), startDate:text("start_date"), dueDate:text("due_date"), labels:text("labels").notNull().default(""), createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`), updatedAt:text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`) }, t=>[index("idx_tickets_status").on(t.status),index("idx_tickets_project_id_status").on(t.projectId,t.status),index("idx_tickets_assignee").on(t.assigneeId),index("idx_tickets_project_status").on(t.project,t.status),index("idx_tickets_due_date").on(t.dueDate)]);
export const ticketActivity = sqliteTable("ticket_activity", { id:integer("id").primaryKey({autoIncrement:true}), ticketId:integer("ticket_id").notNull().references(()=>tickets.id,{onDelete:"cascade"}), userId:text("user_id").notNull(), userName:text("user_name").notNull(), action:text("action").notNull(), detail:text("detail").notNull().default(""), createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) }, t=>[index("idx_activity_ticket_created").on(t.ticketId,t.createdAt)]);
export const ticketComments = sqliteTable("ticket_comments", { id:integer("id").primaryKey({autoIncrement:true}), ticketId:integer("ticket_id").notNull().references(()=>tickets.id,{onDelete:"cascade"}), userId:text("user_id").notNull(), userName:text("user_name").notNull(), body:text("body").notNull(), createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`), updatedAt:text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`) }, t=>[index("idx_comments_ticket_created").on(t.ticketId,t.createdAt)]);
export const ticketAttachments = sqliteTable("ticket_attachments", { id:integer("id").primaryKey({autoIncrement:true}), ticketId:integer("ticket_id").notNull().references(()=>tickets.id,{onDelete:"cascade"}), commentId:integer("comment_id").references(()=>ticketComments.id,{onDelete:"set null"}), uploaderId:text("uploader_id").notNull(), fileKey:text("file_key").notNull().unique(), fileName:text("file_name").notNull(), contentType:text("content_type").notNull(), size:integer("size").notNull(), createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) }, t=>[index("idx_attachments_ticket").on(t.ticketId),index("idx_attachments_comment").on(t.commentId)]);
