import { desc,eq } from "drizzle-orm"; import { getDb } from "../../../../db"; import { profiles,ticketActivity,ticketAttachments,ticketComments,tickets } from "../../../../db/schema"; import { getChatGPTUser } from "../../../chatgpt-auth";import { canEdit,ticketAccess } from "../../../../lib/project-access";
import { validTransition } from "../../../../lib/workflow";
export async function GET(_request:Request,{params}:{params:Promise<{id:string}>}){const user=await getChatGPTUser();if(!user)return Response.json({error:"Authentication required"},{status:401});const {id}=await params,access=await ticketAccess(Number(id),user);if(!access)return Response.json({error:"Ticket not found or access denied"},{status:404});const db=getDb(),activity=await db.select().from(ticketActivity).where(eq(ticketActivity.ticketId,access.ticket.id)).orderBy(desc(ticketActivity.createdAt)).limit(100),comments=await db.select().from(ticketComments).where(eq(ticketComments.ticketId,access.ticket.id)).orderBy(desc(ticketComments.createdAt)).limit(100),attachments=await db.select().from(ticketAttachments).where(eq(ticketAttachments.ticketId,access.ticket.id)).orderBy(desc(ticketAttachments.createdAt));return Response.json({ticket:access.ticket,activity,comments,attachments,role:access.role})}
export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){const user=await getChatGPTUser();if(!user)return Response.json({error:"Authentication required"},{status:401});const {id}=await params,access=await ticketAccess(Number(id),user);if(!access||!canEdit(access.role))return Response.json({error:"Editor access is required"},{status:403});const body=await request.json() as Record<string,unknown>;if(body.status!==undefined&&!validTransition(access.ticket.status,String(body.status)))return Response.json({error:"Invalid workflow transition. Follow the review and QA loop."},{status:400});// A connected agent finishes WORK; it does not finish the TICKET. Resolved is an
// acceptance, and acceptance is a human act - the tool description used to ask an
// agent not to resolve untested work, which is guidance, not a control. Progress
// is refused for the same reason: a percentage an agent chose is a number with no
// evidence behind it, and it reads on the board exactly like a measured one.
if(user.via==="agent"){if(body.status!==undefined&&String(body.status)==="Resolved")return Response.json({error:"A connected agent cannot resolve a ticket. Move it to QA Started and add a comment with your evidence; a person accepts the work."},{status:403});if(body.progress!==undefined)return Response.json({error:"A connected agent cannot set progress. Report what you did in a comment instead."},{status:403});}const db=getDb(),before=access.ticket,allowed=["title","description","issueType","status","priority","assigneeId","assigneeName","progress","storyPoints","startDate","dueDate","labels"] as const,update:Record<string,unknown>={updatedAt:new Date().toISOString()};for(const field of allowed)if(field in body)update[field]=body[field]===""&&["assigneeId","startDate","dueDate","storyPoints"].includes(field)?null:body[field];if("progress" in update)update.progress=Math.max(0,Math.min(100,Number(update.progress)));const [ticket]=await db.update(tickets).set(update).where(eq(tickets.id,Number(id))).returning(),[profile]=await db.select().from(profiles).where(eq(profiles.userId,user.userId)).limit(1),changes=allowed.filter(k=>k in body&&String((before as any)[k]??"")!==String(body[k]??""));await db.insert(ticketActivity).values({ticketId:ticket.id,userId:user.userId,userName:profile?.displayName??user.displayName,action:user.via==="agent"?"updated by agent":"updated",detail:changes.length?changes.map(k=>`${k}: ${String((before as any)[k]??"—")} → ${String(body[k]??"—")}`).join("; "):"Updated ticket"});return Response.json({ticket})}
